// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcV4_mDOv1CKKvfxoqXLFoD2njX4ntW_M',
    appId: '1:671773525922:web:900d574f9e266c270a54fb',
    messagingSenderId: '671773525922',
    projectId: 'ditonton-c4bf6',
    authDomain: 'ditonton-c4bf6.firebaseapp.com',
    storageBucket: 'ditonton-c4bf6.firebasestorage.app',
    measurementId: 'G-4XZLVDZFX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLxi4KLhOSlkBkD8HJLGp5l7rJfaZpRGM',
    appId: '1:671773525922:android:a49c2421d70a31920a54fb',
    messagingSenderId: '671773525922',
    projectId: 'ditonton-c4bf6',
    storageBucket: 'ditonton-c4bf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3eG5aWnZXSnqPgYGqCgtNZW31ejoDkiw',
    appId: '1:671773525922:ios:be4e01645a51dd880a54fb',
    messagingSenderId: '671773525922',
    projectId: 'ditonton-c4bf6',
    storageBucket: 'ditonton-c4bf6.firebasestorage.app',
    iosBundleId: 'com.dicoding.ditonton',
  );

}