// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8dWaBlOsfitC9jn3SXUFsQNmqvyrmYqU',
    appId: '1:644045166569:android:2a1c3a1d2d71c069f89d78',
    messagingSenderId: '644045166569',
    projectId: 'ditonton-28cb6',
    storageBucket: 'ditonton-28cb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrLDPfOHrghcCB1-ve1cfNQl9uUrnHs2E',
    appId: '1:644045166569:ios:f8d74ace312a51e7f89d78',
    messagingSenderId: '644045166569',
    projectId: 'ditonton-28cb6',
    storageBucket: 'ditonton-28cb6.firebasestorage.app',
    iosBundleId: 'com.dicoding.ditonton',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5l5Z0gVpSxaK3pPjgLrQL6XrjfJEav7s',
    appId: '1:644045166569:web:dc09e39d250ab374f89d78',
    messagingSenderId: '644045166569',
    projectId: 'ditonton-28cb6',
    authDomain: 'ditonton-28cb6.firebaseapp.com',
    storageBucket: 'ditonton-28cb6.firebasestorage.app',
    measurementId: 'G-HFR7ZE26TW',
  );

}